version: '3'

services:

  authenticationDatabase:
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
    networks:
      - authNetwork
    volumes:
      - authDBVolume:/var/lib/mysql

  electionDatabase:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - adminNetwork
    volumes:
      - electionDBVolume:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redisNetwork
    volumes:
      - redisVolume:/data

  authentication:
    image: authentication
    environment:
      DATABASE_URL: authenticationDatabase
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      TZ: "Europe/Belgrade"
    depends_on:
      - authenticationDatabase
    command: [ "./wait-for-it.sh", "-t","0", "authenticationDatabase:3306", "--", "gunicorn", "src.application:create_app()" ]
    ports:
      - 5001:5000
    networks:
      - authNetwork


  administrator:
    image: administrator
    environment:
      DATABASE_URL: electionDatabase
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      TZ: "Europe/Belgrade"
    depends_on:
      - electionDatabase
    command: [ "./wait-for-it.sh", "-t","0", "electionDatabase:3306", "--", "gunicorn", "src.application:create_app()" ]
    ports:
      - 5002:5000
    networks:
      - adminNetwork

  zvanicnik:
    image: zvanicnik
    environment:
      REDIS_HOST: redis
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      TZ: "Europe/Belgrade"
    depends_on:
      - redis
    command: [ "./wait-for-it.sh", "-t","0", "redis:6379", "--", "gunicorn", "src.application:create_app()" ]
    ports:
      - 5003:5000
    networks:
      - redisNetwork
    deploy:
      replicas: 3

  daemon:
    image: votingdaemon
    environment:
      REDIS_HOST: redis
      DATABASE_URL: electionDatabase
      TZ: "Europe/Belgrade"
    networks:
      - redisNetwork
      - adminNetwork

networks:
  authNetwork:
    driver: overlay
  adminNetwork:
    driver: overlay
  votingNetwork:
    driver: overlay
  redisNetwork:
    driver: overlay

volumes:
  authDBVolume:
  electionDBVolume:
  redisVolume: