"""Initial database migration

Revision ID: 2e9783159f14
Revises: 
Create Date: 2021-06-24 16:30:35.368825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9783159f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electionparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participantId', sa.Integer(), nullable=False),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['electionId'], ['election.id'], ),
    sa.ForeignKeyConstraint(['participantId'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('pollNumber', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.Column('electionOfficialJmbg', sa.String(length=13), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('electionparticipant')
    op.drop_table('participant')
    op.drop_table('election')
    # ### end Alembic commands ###
